export const updateUserTypes = {
    UDPATE_USER_INPUT_UDPATE: 'UPDATE_USER_INPUT_UPDATE',
    UPDATE_USER_SUBMIT_REQUEST: 'UPDATE_USER_SUBMIT_REQUEST',
    UPDATE_USER_SUBMIT_RESOLVED: 'UPDATE_USER_SUBMIT_RESOLVED'
};



